In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.1549,  1.4304, -0.2999],
        [-0.5411,  0.5759, -0.2817]], requires_grad=True)
tensor([0.4885, 0.8048], requires_grad=True)


In [10]:
def model(x):
    return x @ w.t() + b

In [11]:
preds = model(inputs)
print(preds)

tensor([[ 94.7344, -12.2205],
        [121.2621, -15.7816],
        [188.2397,  14.5651],
        [ 66.6964, -40.0430],
        [127.4982,  -0.9613]], grad_fn=<AddBackward0>)


In [12]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
diff = targets - preds
diff

tensor([[-38.7344,  82.2205],
        [-40.2621, 116.7816],
        [-69.2397, 118.4349],
        [-44.6964,  77.0430],
        [-24.4982, 119.9613]], grad_fn=<SubBackward0>)

In [14]:
diff = preds - targets
diff

tensor([[  38.7344,  -82.2205],
        [  40.2621, -116.7816],
        [  69.2397, -118.4349],
        [  44.6964,  -77.0430],
        [  24.4982, -119.9613]], grad_fn=<SubBackward0>)

In [15]:
diff = preds - targets
diff_sqr = diff * diff
diff_sqr

tensor([[ 1500.3530,  6760.2153],
        [ 1621.0392, 13637.9512],
        [ 4794.1426, 14026.8311],
        [ 1997.7637,  5935.6167],
        [  600.1633, 14390.7129]], grad_fn=<MulBackward0>)

In [16]:
torch.sum(diff_sqr) / diff.numel()

tensor(6526.4790, grad_fn=<DivBackward0>)

In [17]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [20]:
loss = mse(preds, targets)
print(loss)

tensor(6526.4790, grad_fn=<DivBackward0>)


In [21]:
loss.backward()

In [22]:
print(w)
print(w.grad)

tensor([[ 0.1549,  1.4304, -0.2999],
        [-0.5411,  0.5759, -0.2817]], requires_grad=True)
tensor([[ 3752.9458,  3938.0342,  2325.3804],
        [-8613.7559, -9296.9941, -5825.3223]])


In [23]:
print(b)
print(b.grad)

tensor([0.4885, 0.8048], requires_grad=True)
tensor([  43.4862, -102.8883])


In [24]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [25]:
preds = model(inputs)
print(preds)

tensor([[ 94.7344, -12.2205],
        [121.2621, -15.7816],
        [188.2397,  14.5651],
        [ 66.6964, -40.0430],
        [127.4982,  -0.9613]], grad_fn=<AddBackward0>)


In [26]:
loss = mse(preds, targets)
print(loss)

tensor(6526.4790, grad_fn=<DivBackward0>)


In [27]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 3752.9458,  3938.0342,  2325.3804],
        [-8613.7559, -9296.9941, -5825.3223]])
tensor([  43.4862, -102.8883])


In [28]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [29]:
print(w)
print(b)

tensor([[ 0.1174,  1.3910, -0.3232],
        [-0.4549,  0.6689, -0.2235]], requires_grad=True)
tensor([0.4880, 0.8058], requires_grad=True)


In [30]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(4436.2568, grad_fn=<DivBackward0>)


In [31]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [32]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(94.7137, grad_fn=<DivBackward0>)


In [33]:
preds

tensor([[ 58.6336,  71.3923],
        [ 74.9287,  94.8814],
        [132.8866, 144.3851],
        [ 28.3111,  41.8664],
        [ 85.1357, 106.3961]], grad_fn=<AddBackward0>)

In [34]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [41]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [42]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(58.7045, grad_fn=<DivBackward0>)


In [43]:
preds

tensor([[ 58.0617,  71.0508],
        [ 76.2146,  95.9574],
        [130.8816, 142.4868],
        [ 25.1550,  40.0127],
        [ 89.2146, 109.3500]], grad_fn=<AddBackward0>)

In [44]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [45]:
import jovian

In [46]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.ai/martins3569/untitled125


'https://jovian.ai/martins3569/untitled125'

In [47]:
import torch.nn as nn

In [48]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                  [102, 43, 37], [69, 96, 70], [73, 67, 43],
                  [91, 88, 64], [87, 134, 58], [102, 43, 37],
                  [69, 96, 70], [73, 67, 43], [91, 88, 64],
                  [87, 134, 58], [102, 43, 37], [69, 96, 70]],
                 dtype='float32')

targets = np.array([[56, 70], [81, 101], [119, 133],
                   [22, 37], [103, 119], [56, 70],
                   [81, 101], [119, 133], [22, 37],
                   [103, 119], [56, 70], [81, 101],
                   [119, 133], [22, 37], [103, 119]],
                  dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [49]:
from torch.utils.data import TensorDataset

In [50]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [51]:
from torch.utils.data import DataLoader

In [52]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [56]:
for xb, yb in train_dl:
    print('batch:')
    print(xb)
    print(yb)
    #break

batch:
tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [ 56.,  70.],
        [103., 119.],
        [ 56.,  70.]])
batch:
tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 81., 101.],
        [ 56.,  70.],
        [119., 133.],
        [103., 119.]])
batch:
tensor([[102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 91.,  88.,  64.]])
tensor([[ 22.,  37.],
        [ 22.,  37.],
        [119., 133.],
        [ 81., 101.],
        [ 81., 101.]])


In [57]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 56.,  70.]])


In [59]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3638,  0.3310, -0.3394],
        [ 0.2393, -0.4034, -0.2092]], requires_grad=True)
Parameter containing:
tensor([-0.2279,  0.3440], requires_grad=True)


In [60]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3638,  0.3310, -0.3394],
         [ 0.2393, -0.4034, -0.2092]], requires_grad=True),
 Parameter containing:
 tensor([-0.2279,  0.3440], requires_grad=True)]

In [61]:
preds = model(inputs)
preds

tensor([[-19.2016, -18.2130],
        [-25.9258, -26.7710],
        [ -7.2085, -45.0270],
        [-35.6598,  -0.3386],
        [-17.3102, -36.5169],
        [-19.2016, -18.2130],
        [-25.9258, -26.7710],
        [ -7.2085, -45.0270],
        [-35.6598,  -0.3386],
        [-17.3102, -36.5169],
        [-19.2016, -18.2130],
        [-25.9258, -26.7710],
        [ -7.2085, -45.0270],
        [-35.6598,  -0.3386],
        [-17.3102, -36.5169]], grad_fn=<AddmmBackward>)

In [62]:
import torch.nn.functional as F

In [63]:
loss_fn = F.mse_loss

In [64]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(13219.6445, grad_fn=<MseLossBackward>)


In [65]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [66]:
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], loss: {: 4f}'.format(epoch+1, num_epochs, loss.item()))

In [67]:
fit(100, model, loss_fn, opt)

Epoch [10/100], loss:  423.473480
Epoch [20/100], loss:  248.880692
Epoch [30/100], loss:  227.594284
Epoch [40/100], loss:  166.315094
Epoch [50/100], loss:  61.068542
Epoch [60/100], loss:  92.969467
Epoch [70/100], loss:  40.393379
Epoch [80/100], loss:  84.311447
Epoch [90/100], loss:  31.411594
Epoch [100/100], loss:  37.787254


In [68]:
preds = model(inputs)
preds

tensor([[ 58.3506,  72.5168],
        [ 79.0765,  98.4835],
        [125.4458, 135.9186],
        [ 26.5712,  47.9219],
        [ 93.1152, 108.9260],
        [ 58.3506,  72.5168],
        [ 79.0765,  98.4835],
        [125.4458, 135.9186],
        [ 26.5712,  47.9219],
        [ 93.1152, 108.9260],
        [ 58.3506,  72.5168],
        [ 79.0765,  98.4835],
        [125.4458, 135.9186],
        [ 26.5712,  47.9219],
        [ 93.1152, 108.9260]], grad_fn=<AddmmBackward>)

In [69]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [70]:
import jovian

In [71]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "martins3569/untitled125" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/martins3569/untitled125


'https://jovian.ai/martins3569/untitled125'